basePath: /
definitions:
  controller.Info:
    properties:
      message:
        example: 消息
        type: string
      ok:
        example: true
        type: boolean
    type: object
  controller.JSONResult:
    properties:
      code:
        example: 0
        type: integer
      data:
        type: object
      info:
        $ref: '#/definitions/controller.Info'
    type: object
info:
  contact: {}
  description: 网页版kubectl cp
  title: KubeCp Swagger
  version: "1.0"
paths:
  /api/k8s/deployment:
    get:
      description: 命名空间下Deployment资源列表
      parameters:
      - in: query
        name: deployment
        type: string
      - in: query
        name: field_selector
        type: string
      - in: query
        name: label_selector
        type: string
      - in: query
        name: namespace
        type: string
      - in: query
        name: deployment
        type: string
      - in: query
        name: field_selector
        type: string
      - in: query
        name: label_selector
        type: string
      - in: query
        name: namespace
        type: string
      - in: query
        name: deployment
        type: string
      - in: query
        name: field_selector
        type: string
      - in: query
        name: label_selector
        type: string
      - in: query
        name: namespace
        type: string
      - in: query
        name: deployment
        type: string
      - in: query
        name: field_selector
        type: string
      - in: query
        name: label_selector
        type: string
      - in: query
        name: namespace
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.JSONResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.JSONResult'
      summary: ListNamespaceAllDeployment
      tags:
      - Kubernetes
  /api/k8s/download:
    get:
      consumes:
      - application/json
      description: 从容器下载到本地
      parameters:
      - default: default
        description: namespace
        in: query
        name: namespace
        required: true
        type: string
      - default: nginx-test-76996486df-tdjdf
        description: pod_name
        in: query
        name: pod_name
        required: true
        type: string
      - default: nginx-0
        description: container_name
        in: query
        name: container_name
        required: true
        type: string
      - default: /root
        description: dest_path
        in: query
        name: dest_path
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.JSONResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.JSONResult'
      summary: Copy2Local
      tags:
      - Kubernetes
  /api/k8s/exec:
    get:
      description: 在pod的容器中执行
      parameters:
      - collectionFormat: multi
        in: query
        items:
          type: string
        name: command
        type: array
      - in: query
        name: container
        required: true
        type: string
      - in: query
        name: namespace
        required: true
        type: string
      - in: query
        name: pods
        required: true
        type: string
      - in: query
        name: stderr
        type: boolean
      - in: query
        name: stdout
        type: boolean
      - in: query
        name: tty
        type: boolean
      - collectionFormat: multi
        in: query
        items:
          type: string
        name: command
        type: array
      - in: query
        name: container
        required: true
        type: string
      - in: query
        name: namespace
        required: true
        type: string
      - in: query
        name: pods
        required: true
        type: string
      - in: query
        name: stderr
        type: boolean
      - in: query
        name: stdout
        type: boolean
      - in: query
        name: tty
        type: boolean
      - collectionFormat: multi
        in: query
        items:
          type: string
        name: command
        type: array
      - in: query
        name: container
        required: true
        type: string
      - in: query
        name: namespace
        required: true
        type: string
      - in: query
        name: pods
        required: true
        type: string
      - in: query
        name: stderr
        type: boolean
      - in: query
        name: stdout
        type: boolean
      - in: query
        name: tty
        type: boolean
      - collectionFormat: multi
        in: query
        items:
          type: string
        name: command
        type: array
      - in: query
        name: container
        required: true
        type: string
      - in: query
        name: namespace
        required: true
        type: string
      - in: query
        name: pods
        required: true
        type: string
      - in: query
        name: stderr
        type: boolean
      - in: query
        name: stdout
        type: boolean
      - in: query
        name: tty
        type: boolean
      - collectionFormat: multi
        in: query
        items:
          type: string
        name: command
        type: array
      - in: query
        name: container
        required: true
        type: string
      - in: query
        name: namespace
        required: true
        type: string
      - in: query
        name: pods
        required: true
        type: string
      - in: query
        name: stderr
        type: boolean
      - in: query
        name: stdout
        type: boolean
      - in: query
        name: tty
        type: boolean
      - collectionFormat: multi
        in: query
        items:
          type: string
        name: command
        type: array
      - in: query
        name: container
        required: true
        type: string
      - in: query
        name: namespace
        required: true
        type: string
      - in: query
        name: pods
        required: true
        type: string
      - in: query
        name: stderr
        type: boolean
      - in: query
        name: stdout
        type: boolean
      - in: query
        name: tty
        type: boolean
      - collectionFormat: multi
        in: query
        items:
          type: string
        name: command
        type: array
      - in: query
        name: container
        required: true
        type: string
      - in: query
        name: namespace
        required: true
        type: string
      - in: query
        name: pods
        required: true
        type: string
      - in: query
        name: stderr
        type: boolean
      - in: query
        name: stdout
        type: boolean
      - in: query
        name: tty
        type: boolean
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.JSONResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.JSONResult'
      summary: Container 执行器
      tags:
      - Kubernetes
  /api/k8s/multi_upload:
    post:
      consumes:
      - multipart/form-data
      description: 上传到容器
      parameters:
      - default: default
        description: namespace
        in: query
        name: namespace
        required: true
        type: string
      - default: nginx-test-76996486df-tdjdf
        description: pod_name
        in: query
        name: pod_name
        required: true
        type: string
      - default: /root/
        description: dest_path
        in: query
        name: dest_path
        type: string
      - description: files
        in: formData
        name: files
        required: true
        type: file
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.JSONResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.JSONResult'
      summary: MultiCopy2Container
      tags:
      - Kubernetes
  /api/k8s/namespace:
    get:
      description: 命名空间列表
      parameters:
      - in: query
        name: field_selector
        type: string
      - in: query
        name: label_selector
        type: string
      - in: query
        name: namespace
        type: string
      - in: query
        name: field_selector
        type: string
      - in: query
        name: label_selector
        type: string
      - in: query
        name: namespace
        type: string
      - in: query
        name: field_selector
        type: string
      - in: query
        name: label_selector
        type: string
      - in: query
        name: namespace
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.JSONResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.JSONResult'
      summary: ListNamespace
      tags:
      - Kubernetes
  /api/k8s/pods:
    get:
      description: 命名空间下Pod资源列表
      parameters:
      - in: query
        name: field_selector
        type: string
      - in: query
        name: label_selector
        type: string
      - in: query
        name: namespace
        type: string
      - in: query
        name: pod
        type: string
      - in: query
        name: field_selector
        type: string
      - in: query
        name: label_selector
        type: string
      - in: query
        name: namespace
        type: string
      - in: query
        name: pod
        type: string
      - in: query
        name: field_selector
        type: string
      - in: query
        name: label_selector
        type: string
      - in: query
        name: namespace
        type: string
      - in: query
        name: pod
        type: string
      - in: query
        name: field_selector
        type: string
      - in: query
        name: label_selector
        type: string
      - in: query
        name: namespace
        type: string
      - in: query
        name: pod
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.JSONResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.JSONResult'
      summary: ListNamespaceAllSource
      tags:
      - Kubernetes
  /api/k8s/status:
    get:
      description: 获取pod中container状态
      parameters:
      - in: query
        name: deployment
        type: string
      - in: query
        name: field_selector
        type: string
      - in: query
        name: label_selector
        type: string
      - in: query
        name: namespace
        required: true
        type: string
      - in: query
        name: deployment
        type: string
      - in: query
        name: field_selector
        type: string
      - in: query
        name: label_selector
        type: string
      - in: query
        name: namespace
        required: true
        type: string
      - in: query
        name: deployment
        type: string
      - in: query
        name: field_selector
        type: string
      - in: query
        name: label_selector
        type: string
      - in: query
        name: namespace
        required: true
        type: string
      - in: query
        name: deployment
        type: string
      - in: query
        name: field_selector
        type: string
      - in: query
        name: label_selector
        type: string
      - in: query
        name: namespace
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.JSONResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.JSONResult'
      summary: PodStatus
      tags:
      - Kubernetes
  /api/k8s/terminal:
    get:
      description: pod 中容器的终端
      parameters:
      - in: query
        name: container
        required: true
        type: string
      - in: query
        name: namespace
        required: true
        type: string
      - in: query
        name: pods
        required: true
        type: string
      - in: query
        name: shell
        type: string
      - in: query
        name: container
        required: true
        type: string
      - in: query
        name: namespace
        required: true
        type: string
      - in: query
        name: pods
        required: true
        type: string
      - in: query
        name: shell
        type: string
      - in: query
        name: container
        required: true
        type: string
      - in: query
        name: namespace
        required: true
        type: string
      - in: query
        name: pods
        required: true
        type: string
      - in: query
        name: shell
        type: string
      - in: query
        name: container
        required: true
        type: string
      - in: query
        name: namespace
        required: true
        type: string
      - in: query
        name: pods
        required: true
        type: string
      - in: query
        name: shell
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.JSONResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.JSONResult'
      summary: Container terminal
      tags:
      - Kubernetes
  /api/k8s/upload:
    post:
      consumes:
      - multipart/form-data
      description: 上传到容器
      parameters:
      - default: default
        description: namespace
        in: query
        name: namespace
        required: true
        type: string
      - default: nginx-test-76996486df-tdjdf
        description: pod_name
        in: query
        name: pod_name
        required: true
        type: string
      - default: nginx-0
        description: container_name
        in: query
        name: container_name
        required: true
        type: string
      - default: /root/
        description: dest_path
        in: query
        name: dest_path
        type: string
      - description: files
        in: formData
        name: files
        required: true
        type: file
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.JSONResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.JSONResult'
      summary: Copy2Container
      tags:
      - Kubernetes
swagger: "2.0"
