name: Build image
on:
  push:
    branches: [ mian ]
  pull_request:
    branches: [ main ]
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: docker build --network host --rm --build-arg APP_ROOT=/go/src/kubefilebrowser -t ${{ secrets.DOCKER_REPOSITORY }}:latest -f Dockerfile .
      - name: Login to registry
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY }}
      - name: Push Image
        run: docker push ${{ secrets.DOCKER_REPOSITORY }}:latest