name: Build image
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        id: install_golang
        uses: actions/setup-go@v2
        with:
          go-version: "v1.16.2"
      - name: build kf_tools
        run: sh 00-build_lib.sh
      - name: Build Image
        run: docker build --build-arg APP_ROOT=/go/src/kubefilebrowser -t ${{ secrets.DOCKER_REPOSITORY }}:latest -f Dockerfile .
      - name: Login to registry
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY }}
      - name: image list
        run: docker images
      - name: Push Image
        run: docker push ${{ secrets.DOCKER_REPOSITORY }}:latest